export const IPC_CHANNELS = {
  gmailState: "gmail:state",
  gmailImport: "gmail:import",
  gmailConnect: "gmail:connect",
  gmailCheck: "gmail:check",
  gmailAutomatic: "gmail:automatic",
  gmailRecentOnly: "gmail:recent-only",
  gmailDisconnect: "gmail:disconnect",
  gmailDismiss: "gmail:dismiss",
  gmailApply: "gmail:apply",
  gmailCancel: "gmail:cancel",
  listApplications: "applications:list",
  searchDiscoveredJobs: "discover:search",
  saveDiscoveredJob: "discover:save",
  visitDiscoveredJob: "discover:visit",
  updateDeadline: "applications:update-deadline",
  moveApplication: "applications:move",
  evaluateFollowUps: "applications:evaluate-follow-ups",
  dismissFollowUp: "applications:dismiss-follow-up",
  deleteApplication: "applications:delete",
  getProfile: "profile:get",
  saveProfile: "profile:save",
  getMasterResume: "resume:get-master",
  saveMasterResume: "resume:save-master",
  bridgeInfo: "bridge:info",
} as const;
